# Generated by Django 4.2.19 on 2025-03-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_page_is_read_page_receiver_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='page',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
